# Generated by Django 4.1.1 on 2022-09-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='lagos', max_length=50),
        ),
    ]
