# Generated by Django 4.1.1 on 2022-09-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0002_user_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Give',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, choices=[('fur', 'Furniture'), ('clo', 'Clothes'), ('sho', 'Shoes'), ('toy', 'toys'), ('ele', 'Electronics'), ('bag', 'Bags'), ('fon', 'mobile-phones'), ('lap', 'Laptops'), ('buk', 'Books'), ('kit', 'Kitchen-utensils'), ('bic', 'Bicyle'), ('ace', 'Accessories'), ('fud', 'Food-stuffs'), ('gro', 'Groceries'), ('gen', 'Generator'), ('bty', 'Beauty-product'), ('nat', 'Natives')], default='', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='givers/images/')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='', max_length=10)),
                ('quantity', models.IntegerField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_requested', models.DateTimeField(blank=True, null=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('gift_recipient', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(choices=[('lagos', 'Lagos'), ('ogun', 'Ogun'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('ondo', 'Ondo'), ('kwara', 'Kwara'), ('niger', 'Niger'), ('nassarawa', 'Nassarawa'), ('plateau', 'Plateau'), ('abuja', 'Abuja'), ('edo', 'Edo'), ('abia', 'Abia'), ('akwa-ibom', 'Akwa-Ibom'), ('adamawa', 'Adamawa'), ('anambra', 'Anambra'), ('cross-river', 'Cross-River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('benue', 'Benue'), ('bayelsa', 'Bayelsa'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('jigawa', 'Jigawa'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kogi', 'Kogi'), ('kebbi', 'Kebbi'), ('kaduna', 'Kaduna'), ('imo', 'Imo'), ('borno', 'Borno'), ('gombe', 'Gombe'), ('rivers', 'Rivers'), ('zamfara', 'Zamfara'), ('yobe', 'Yobe'), ('sokoto', 'Sokoto')], max_length=40)),
                ('gift_status', models.CharField(blank=True, choices=[('unpicked', 'unpicked'), ('delivered', 'delivered'), ('on-delivery', 'on-delivery'), ('paid', 'paid')], default='unpicked', max_length=30)),
            ],
        ),
    ]
