# Generated by Django 4.1.1 on 2022-10-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0005_order_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dispatch_partner',
        ),
    ]
