# Generated by Django 4.1.1 on 2022-10-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0006_remove_order_dispatch_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(default='Lagos', max_length=50),
        ),
    ]
