# Generated by Django 4.1.1 on 2022-10-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0008_remove_transaction_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
