# Generated by Django 4.1.1 on 2022-10-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0010_alter_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
