# Generated by Django 4.1.1 on 2022-10-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0011_alter_order_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
