# Generated by Django 4.1.1 on 2022-10-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0012_delete_transaction_alter_order_ordered_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_ids',
            field=models.JSONField(default=list, null=True),
        ),
    ]
