# Generated by Django 4.1.1 on 2022-10-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0015_alter_give_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ref', models.CharField(blank=True, max_length=40, null=True)),
                ('date_raised', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('treated', models.BooleanField(default=False)),
            ],
        ),
    ]
