# Generated by Django 4.1.1 on 2022-10-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0017_product_delete_give'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='price',
        ),
    ]
