# Generated by Django 4.1.1 on 2022-10-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0022_rename_quantity_in_cart_shoppingcart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('in-cart', 'in-cart'), ('ordered', 'ordered')], default='in-cart', max_length=20),
        ),
    ]
