# Generated by Django 4.1.1 on 2022-10-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0023_alter_shoppingcart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
