# Generated by Django 4.1.1 on 2022-10-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0024_shoppingcart_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
