# Generated by Django 4.1.1 on 2022-10-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0025_remove_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.ImageField(blank=True, upload_to='givers/images/')),
                ('videofile', models.FileField(null=True, upload_to='givers/videos')),
            ],
        ),
    ]
