# Generated by Django 4.1.1 on 2022-10-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0026_homepagevideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AddField(
            model_name='homepagevideo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
