# Generated by Django 4.1.1 on 2022-10-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0027_alter_contactus_options_homepagevideo_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_sales',
            field=models.BooleanField(default=False),
        ),
    ]
