# Generated by Django 4.1.1 on 2022-12-26 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0030_alter_shoppingcart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='givers/videos'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='givers.product'),
        ),
    ]
