# Generated by Django 4.1.1 on 2022-12-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0031_product_videofile_alter_shoppingcart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('furniture', 'Furniture'), ('clothe', 'Clothes'), ('shoe', 'Shoes'), ('toy', 'toys'), ('electronics', 'Electronics'), ('bag', 'Bags'), ('mobile', 'mobile-phones'), ('bathroom', 'Bathroom'), ('tracker', 'Tracker'), ('kitchen', 'Kitchen'), ('household-accessories', 'Household-accessories'), ('accessories', 'Accessories'), ('beauty', 'Beauty')], default='', max_length=50),
        ),
    ]
