# Generated by Django 4.1.1 on 2023-01-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0032_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationcharge',
            name='door_delivery_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destinationcharge',
            name='city',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
    ]
