# Generated by Django 4.1.1 on 2023-01-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givers', '0035_alter_store_total_alter_store_unit_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='unit_sold',
            field=models.IntegerField(default=0),
        ),
    ]
