# Generated by Django 4.1.1 on 2023-02-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("givers", "0037_delete_charge_alter_product_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
