# Generated by Django 4.1.1 on 2023-02-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("givers", "0038_user_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="active",
        ),
    ]
