# Generated by Django 4.1.1 on 2023-02-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("givers", "0039_remove_user_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
    ]
