# Generated by Django 4.1.1 on 2023-05-11 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("givers", "0041_alter_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="in_stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="store",
            name="product",
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="ProductVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant", models.CharField(blank=True, max_length=50, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(default=0)),
                ("in_stock", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant",
                        to="givers.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("variant", "product")},
            },
        ),
        migrations.AddField(
            model_name="store",
            name="variant",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="givers.productvariation",
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopping_cart",
                to="givers.productvariation",
            ),
        ),
    ]
