# Generated by Django 4.1.1 on 2023-05-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("givers", "0042_remove_product_in_stock_remove_product_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="productvariation",
            name="price",
            field=models.IntegerField(default=1000),
        ),
    ]
