# Generated by Django 4.1.1 on 2023-05-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("givers", "0043_remove_product_price_productvariation_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="destinationcharge",
            name="zone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("island zone A", "island zone A"),
                    ("island zone B", "island zone B"),
                    ("island zone B2", "island zone B2"),
                    ("mainland zone A", "mainland zone A"),
                    ("mainland zone B", "mainland zone B"),
                    ("mainland zone C", "mainland zone C"),
                    ("mainland zone D", "mainland zone D"),
                    ("mainland zone E", "mainland zone E"),
                ],
                default="",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="zone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
